---
- gz_topic_name: "/clock"
  gz_type_name: "gz.msgs.Clock"
  ros_topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  direction: GZ_TO_ROS

- gz_topic_name: "/world/empty/model/so_arm_100/joint_state"
  gz_type_name: "gz.msgs.Model"
  ros_topic_name: "robot_joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  direction: GZ_TO_ROS

- gz_topic_name: "/model/so_arm_100/joint/Shoulder_Rotation/0/cmd_pos"
  gz_type_name: "gz.msgs.Double"
  ros_topic_name: "shoulder_rotation/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  direction: ROS_TO_GZ

- gz_topic_name: "/model/so_arm_100/joint/Shoulder_Pitch/0/cmd_pos"
  gz_type_name: "gz.msgs.Double"
  ros_topic_name: "shoulder_pitch/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  direction: ROS_TO_GZ

- gz_topic_name: "/model/so_arm_100/joint/Elbow/0/cmd_pos"
  gz_type_name: "gz.msgs.Double"
  ros_topic_name: "elbow/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  direction: ROS_TO_GZ

- gz_topic_name: "/model/so_arm_100/joint/Wrist_Pitch/0/cmd_pos"
  gz_type_name: "gz.msgs.Double"
  ros_topic_name: "wrist_pitch/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  direction: ROS_TO_GZ

- gz_topic_name: "/model/so_arm_100/joint/Wrist_Roll/0/cmd_pos"
  gz_type_name: "gz.msgs.Double"
  ros_topic_name: "wrist_roll/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  direction: ROS_TO_GZ

- gz_topic_name: "/model/so_arm_100/joint/Gripper/0/cmd_pos"
  gz_type_name: "gz.msgs.Double"
  ros_topic_name: "gripper/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  direction: ROS_TO_GZ

